import { type NextPage } from "next";
import Head from "next/head";

import { signOut, useSession } from "next-auth/react";
import { LogOut } from "lucide-react";
import * as DropdownMenu from "~/components/ui/DropdownMenu";

function User() {
  const { data } = useSession();
  const splitedName = data?.user.name?.split(" ");

  const firstInitial =
    splitedName !== undefined && splitedName[0] ? splitedName[0].charAt(0) : "";
  const secondInitial =
    splitedName !== undefined && splitedName[1] ? splitedName[1].charAt(0) : "";

  return (
    <DropdownMenu.Root>
      <DropdownMenu.Trigger className="flex h-7 w-7 items-center justify-center rounded-md bg-zinc-700">
        <strong className="text-xs uppercase tracking-widest">
          {`${firstInitial}${secondInitial}`}
        </strong>
      </DropdownMenu.Trigger>

      <DropdownMenu.Content className="w-48 rounded-md p-3">
        <DropdownMenu.Item className="rounded-md p-2">
          Profile
        </DropdownMenu.Item>
        <DropdownMenu.Separator />
        <DropdownMenu.Item asChild className="rounded-md p-2">
          <button
            type="button"
            className="inline-flex w-full cursor-pointer items-center text-red-500"
            onClick={() => void signOut()}
          >
            <LogOut className="mr-2 h-5 w-5" />
            Logout
          </button>
        </DropdownMenu.Item>
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  );
}

function Header() {
  return (
    <header className="bg-zinc-950/70 sticky inset-x-0 top-0 z-30 flex h-11 items-center justify-between py-1.5 px-2">
      <div className=""></div>
      <User />
    </header>
  );
}

function Sidebar() {
  return (
    <aside className="sticky top-11 left-0 z-20 flex h-full max-h-full flex-col justify-between overflow-y-auto bg-zinc-800">
      <div className="py-3">
        <div className="flex justify-between px-4">
          <strong className="text-lg">Channels</strong>
          <button
            type="button"
            className="flex h-8 w-8 items-center justify-center rounded-md bg-zinc-700 shadow"
          >
            +
          </button>
        </div>

        <p className="my-80">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos
          asperiores in nemo velit perspiciatis culpa blanditiis consequatur
          nobis porro officia? Quo consequuntur ullam fugiat natus dolor quos
          facilis cum exercitationem.
        </p>
      </div>
    </aside>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full max-h-screen overflow-hidden">
        <Header />
        <div className="grid grid-cols-[16rem_1fr] grid-rows-1">
          <Sidebar />

          <div className="h-full p-2">
            <div className="max-h-[30rem] overflow-y-auto ">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim,
              aliquam dolore sint aperiam id obcaecati consectetur. Dolore
              veritatis excepturi nisi impedit iure dignissimos possimus soluta
              quod, sequi voluptatum, ex adipisci? Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Enim, aliquam dolore sint aperiam id
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim,
              aliquam dolore sint aperiam id obcaecati consectetur. Dolore
              veritatis excepturi nisi impedit iure dignissimos possimus soluta
              quod, sequi voluptatum, ex adipisci? Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Enim, aliquam dolore sint aperiam id
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim,
              aliquam dolore sint aperiam id obcaecati consectetur. Dolore
              veritatis excepturi nisi impedit iure dignissimos possimus soluta
              quod, sequi voluptatum, ex adipisci? Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Enim, aliquam dolore sint aperiam id
              obcaecati consectetur. Dolore veritatis excepturi nisi impedit
              iure dignissimos possimus soluta quod, sequi voluptatum, ex
              adipisci? Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Enim, aliquam dolore sint aperiam id obcaecati consectetur. Dolore
              veritatis excepturi nisi impedit iure dignissimos possimus soluta
              quod, sequi voluptatum, ex adipisci? Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Enim, aliquam dolore sint aperiam id
              obcaecati consectetur. Dolore veritatis excepturi nisi impedit
              iure dignissimos possimus soluta quod, sequi voluptatum, ex
              adipisci? veritatis excepturi nisi impedit iure dignissimos
              possimus soluta quod, sequi voluptatum, ex adipisci? Lorem ipsum
              dolor sit amet consectetur adipisicing elit. Enim, aliquam dolore
              sint aperiam id obcaecati consectetur. Dolore veritatis excepturi
              nisi impedit iure dignissimos possimus soluta quod, sequi
              voluptatum, ex adipisci? veritatis excepturi nisi impedit iure
              dignissimos possimus soluta quod, sequi voluptatum, ex adipisci?
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim,
              aliquam dolore sint aperiam id obcaecati consectetur. Dolore
              veritatis excepturi nisi impedit iure dignissimos possimus soluta
              quod, sequi voluptatum, ex adipisci? veritatis excepturi nisi
              impedit iure dignissimos possimus soluta quod, sequi voluptatum,
              ex adipisci? Lorem ipsum dolor sit amet consectetur adipisicing
              elit. Enim, aliquam dolore sint aperiam id obcaecati consectetur.
              Dolore veritatis excepturi nisi impedit iure dignissimos possimus
              soluta quod, sequi voluptatum, ex adipisci? veritatis excepturi
              nisi impedit iure dignissimos possimus soluta quod, sequi
              voluptatum, ex adipisci? Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Enim, aliquam dolore sint aperiam id obcaecati
              consectetur. Dolore veritatis excepturi nisi impedit iure
              dignissimos possimus soluta quod, sequi voluptatum, ex adipisci?
              veritatis excepturi nisi impedit iure dignissimos possimus soluta
              quod, sequi voluptatum, ex adipisci? Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Enim, aliquam dolore sint aperiam id
              obcaecati consectetur. Dolore veritatis excepturi nisi impedit
              iure dignissimos possimus soluta quod, sequi voluptatum, ex
              adipisci?
            </div>

            <div className="">Chat box</div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
